### ISSUE TITLE
Sample Stylesheet for Gantt vs Sequence Diagram

### ISSUE THREAD

**Issue by banjavi** [mermaidjs/mermaid-gitbook#13]
I noticed the "Sample Stylesheets" for the Gantt and Sequence Diagram pages are different on the gitbook site, but that the "Classes used" are the same. Does the section "Classes used" on https://mermaidjs.github.io/gantt.html need to be updated?  I'm trying to style a Gantt diagram (fix margin issues on the rects, move elements, etc.), but have been unsuccessful so far.

**Comment by tylerlong** [comment]
Here is the latest SCSS: https://github.com/knsv/mermaid/blob/master/src/themes/gantt.scss

The doc is quite dated. It is appreciate if you could contribute a PR.

**Comment by tylerlong** [comment]
And CSS is not the only way to change margin. Please refer the following code:

```js
mermaid.initialize({gantt: {
  titleTopMargin: 25,
  barHeight: 20,
  barGap: 4,
  topPadding: 50,
  rightPadding: 75,
  leftPadding: 75,
  gridLineStartPadding: 35,
  fontSize: 11,
  fontFamily: '"Open-Sans", "sans-serif"'
}})
```
