### ISSUE TITLE
Sequence diagram participant aliasing isn't documented

### ISSUE THREAD

**Issue by leftiness** [mermaidjs/mermaid-gitbook#3]
knsv/mermaid#265 added support for aliasing sequence diagram participants. This isn't mentioned in the [sequence diagram documentation](../blob/master/content/sequenceDiagram.md). I'll make you a pull request this evening when I'm off work. :)

Example:

```
sequenceDiagram

participant a as alice
participant b as bob

a ->> b: hello
```

**Comment by tylerlong** [comment]
Many thanks! Merged!
