### ISSUE TITLE
If 'o' is the first letter, graph won't show any thing like A--o-->B

### ISSUE THREAD

**Issue by tgsmdww** [mermaidjs/mermaid-gitbook#34]
Like this,
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --o--> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[fa:fa-car Car]

Parse error on line 3:
...B(Go shopping)B --o--> C{Let me think}
----------------------^
Expecting 'DIR', 'DOWN', 'MINUS', 'TESTSTR', 'PIPE', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', got 'ARROW_POINT'

It works if I use &#111

**Comment by renanlecaro** [comment]
This seems to be an issue with https://github.com/knsv/mermaid and not with this repository (this repo is only for the gitbook documentation)

**Comment by tgsmdww** [comment]
I'm sorry
